create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

grant usage on schema public to anon, authenticated;
grant select on table public.todos to anon, authenticated;

drop policy if exists "Todos are publicly readable" on public.todos;

create policy "Todos are publicly readable"
on public.todos
for select
to anon, authenticated
using (true);

insert into public.todos (name)
values
  ('Crear una tabla de ejemplo'),
  ('Conectar Next.js con Supabase'),
  ('Renderizar datos desde Server Components')
on conflict do nothing;
